### ISSUE TITLE
High failure rates for Team Open Science Grid

### ISSUE THREAD

**Issue by jchodera** [djw8605/covid-submit#1]
@djw8605 : I'm not sure if you're the appropriate contact, but we ([the Folding@home Consortium](https://foldingathome.org/about/the-foldinghome-consortium/)) have been seeing persistent high failure rates for Folding@home clients run by [Team Open Science Grid](https://stats.foldingathome.org/team/258507). For example, there are many instances in the stats database where a client run by Team Open Science Grid fails repeatedly before another client completes the work unit:
![image](https://user-images.githubusercontent.com/3656088/99035135-ce526c00-2533-11eb-9bf0-2ef32df55825.png)

We suspect something is misconfigured with whoever is running these FAH clients, and are looking to get in touch with them. Do you know if this workflow is currently in use?

Note that the [official Folding@home client Docker image](https://github.com/FoldingAtHome/containers) is actively maintained both by Folding@home and NVIDIA devs, and we can ensure that it is configured properly.

**Comment by djw8605** [comment]
Hi, yes, I am exactly the right person to contact for Folding@Home on the Open Science Grid.  I will take a look at these failures this morning.

**Comment by jchodera** [comment]
Thanks, @djw8605! Feel free to ping me or @beberg (who built the official Folding@home Docker container) if we can be of any help!

**Comment by djw8605** [comment]
Mid day update.  
​
I have refactored the current covid flow to use the official docker containers.  I've sent test jobs to the OSG, and they have been running for 1-2 hours now.  When they complete (GPU job will likely complete in a hour or 2, the CPU job will likely take a day), I will analyze the logs to make sure everything was successful.  Especially that the GPU job correctly detected and is using the GPU.

**Comment by jchodera** [comment]
@djw8605 : Awesome! Thanks so much! 

If you want us to check things on the server side, just let us know which (PROJ,RUN,CLONE,GEN) tuples were processed and we can look things up here.

**Comment by djw8605** [comment]
Another update.  The CPU-Only version worked great!  But... the GPU version has yet to complete.  Since it has been several days, I suspect the GPU job is not working or just stalling.

Is there a setting that says: "Wait up to X Minutes for work and exit if it does not receive any".  The current command line for the client I have is:

    FAHClient --user=Anonymous --team=258507 --gpu=true --smp=true --cpus=1 --exit-when-done=true --max-units=1 --cause=covid-19

**Comment by jchodera** [comment]
> Is there a setting that says: "Wait up to X Minutes for work and exit if it does not receive any". 
Tagging @jcoffland for help here. See above, @jcoffland.

I'd be *very* surprised if we had a GPU WU deficit, since we have a huge number of pending jobs in the system. Could something else be going on? Are you able to retrieve the client logs from these fahclient GPU workers?

**Comment by djw8605** [comment]
You are right.  After some investigation, I discovered that the issue is that both a CPU and GPU jobs are running.  The GPU job takes a few hours, while the CPU one can take 20+ hours.  Do you have an example of a config (or, command line) that would only let a GPU job to run, and no CPU jobs?

**Comment by jcoffland** [comment]
```
<config>
  <auto-conf v="false"/>
  <slot type="GPU"/>
</config>
```

You could also include your command line arguments like this:

```
<config>
  <user v="Anonymous"/>
  <team v="258507"/>
  <exit-when-done/>
  <max-units v="1"/>
  <cause v="covid-19"/>
  <auto-conf v="false"/>
  <slot type="GPU"/>
</config>
```

I left out the options that aren't necessary.

There is currently no way to wait for X minutes for work.

**Comment by djw8605** [comment]
That configuration worked.  I had to add `id` to the slot element, but then it worked.  I will implement this for all of the COVID jobs.

Here is a GPU job information so you can check:
project:13429 run:7772 clone:24 gen:1 core:0x22 unit:0x0000000112bc7d9a000000001e5c0018

**Comment by jchodera** [comment]
Completed without incident!

Performance was oddly variable throughout the run, though:
```
$ grep Performance PROJ13429/RUN7772/CLONE24/results1/science.log 
  Performance since last checkpoint: 217.0854271 ns/day
  Performance since last checkpoint: 220.4081633 ns/day
  Performance since last checkpoint: 214.9253731 ns/day
  Performance since last checkpoint: 214.9253731 ns/day
  Performance since last checkpoint: 200 ns/day
  Performance since last checkpoint: 212.8078818 ns/day
  Performance since last checkpoint: 212.8078818 ns/day
  Performance since last checkpoint: 191.1504425 ns/day
  Performance since last checkpoint: 218.1818182 ns/day
  Performance since last checkpoint: 212.8078818 ns/day
  Performance since last checkpoint: 214.9253731 ns/day
  Performance since last checkpoint: 196.3636364 ns/day
  Performance since last checkpoint: 213.8613861 ns/day
  Performance since last checkpoint: 211.7647059 ns/day
  Performance since last checkpoint: 208.6956522 ns/day
  Performance since last checkpoint: 212.8078818 ns/day
  Performance since last checkpoint: 211.7647059 ns/day
  Performance since last checkpoint: 195.4751131 ns/day
  Performance since last checkpoint: 153.1914894 ns/day
  Performance since last checkpoint: 217.0854271 ns/day
```
Is this expected since there is other load on these machines?

**Comment by djw8605** [comment]
Yes, it could be variable due to many other jobs running on these nodes.  It should have a "Dedicated" GPU, but the load on the processor and/or bus may be variable.

Ok, tomorrow I will push out my changes to all of the OSG's F@H work.

**Comment by anand-bhat** [comment]
Does this set of changes also include support for persistent storage? I'm particularly invested in the file (client.db) that has the CPU identifier and the science (core) executables being [reused across sessions.](https://github.com/FoldingAtHome/containers#operating-containers)

**Comment by jchodera** [comment]
Thanks so much, @djw8605!

@anand-bhat : As long as the client is allowed to run to completion, it will complete one WU and terminate. If the job is preempted, all work up to that point will be lost if there is no persistent storage.

**Comment by djw8605** [comment]
Indeed, on the OSG, preemption is common.  But, the client usually has no "signal" to cleanup and stage out before preemption.  In fact, SLURM will just kill the cgroup and delete the working directory without sending a signal to the underlying processes.  That is why we want to only run 1 task per job, lots of job turnover is fine in the OSG.

**Comment by djw8605** [comment]
Hi @jchodera, a day late, but I just deployed the changes.  Is there a way to watch the failure rates for my team?  Should I just check in with you early next week?

**Comment by djw8605** [comment]
Hi @jchodera, I hope the OSG's failure rate is much better.

**Comment by anand-bhat** [comment]
Hi @djw8605, I do not see any new failures from the OSG clients now. Awesome!

**Comment by djw8605** [comment]
Great!  thanks!
